global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "producer"
    static_configs:
      - targets:
          - "producer1:8001"
          - "producer2:8004"
          - "producer3:8005"

  - job_name: "consumer"
    static_configs:
      - targets:
          - "consumer1:8002"
          - "consumer2:8003"
